#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$steak = new Parsnick\Steak\Application(new Illuminate\Container\Container(), '1.0.0');


/*
$steak->bootstrap([
    // ReadConfig
]);

$steak->pipeline([
    // SkipUnderscored
    // CompileBlade
    // CompilePhp
]);*/

$steak->commands([
    // InitCommand
    Parsnick\Steak\Console\BuildCommand::class,
    // ServeCommand
    // SyncCommand (pull)
    // DeployCommand (push)
]);

$steak->run();