#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$container = new Illuminate\Container\Container();

$app = new Symfony\Component\Console\Application('Steak', '1.0.0');
$app->add(
    $container->make(Parsnick\Steak\Console\BuildCommand::class)
);

$app->run();