#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$steak = new Parsnick\Steak\Application('1.0.0');

$steak->commands([
    Parsnick\Steak\Console\InitCommand::class,
    Parsnick\Steak\Console\BuildCommand::class,
    Parsnick\Steak\Console\ServeCommand::class,
    Parsnick\Steak\Console\StatusCommand::class,
    Parsnick\Steak\Console\PullCommand::class,
    Parsnick\Steak\Console\DeployCommand::class,
]);

$steak->run();

